package ru.rpuxa.messenger.model.server

enum class Error(val code: Int) {
    NO_ERROR(0),
    WRONG_ARGS(1),
    UNKNOWN_TOKEN(2),
    UNKNOWN_ID(3),

    UNKNOWN_USER_FIELD(200),
    CURRENT_PASSWORD_NEEDED(201),
    CURRENT_PASSWORD_WRONG(202),

    ACCOUNT_IS_NOT_FOUND(400),
    ALREADY_IN_FRIENDS(401),
    ALREADY_SENT_REQUEST(402),
    REQUEST_NOT_FOUND(403),
    CANT_SEND_REQUEST_TO_YOURSELF(404),
    ;
}